### ISSUE TITLE
Preview images and screenshots do not show revised desktop layout

### ISSUE THREAD

**Issue by fossfreedom** [budgie-remix/ubiquity-slideshow-budgie-remix#2]
Screenshots in the slideshow do not show centered clock nor does it show the dock.:worried: It needs to remove the icon-taskbar applet as well.

**Comment by RohanVilloth** [comment]
K.. I'll update the package soon..ish. Was waiting to see if there'll be more changes in interface. :smile: How about something similar to this?:

![budgie-remixReleaseCandidate](https://cloud.githubusercontent.com/assets/3755396/14587003/6bd20f86-04c7-11e6-9d1a-9c3f249e0b41.png)

It does show centered clock and Plank dock, but I've no idea where the 'to be removed' icon-taskbar applet is. :open_mouth:

**Comment by fossfreedom** [comment]
I wouldn't worry.  Just needs to be tidied for the next release in July.

The icon thingy was the list of icons next to the start button.  As you can see in your screenshot it is no longer there

**Comment by RohanVilloth** [comment]
Aah, the tasklist applet! How could I forget it's name :sweat_smile: . K.. I'll update slideshow with screenshots from the RC u released yesterday :relaxed:

**Comment by RohanVilloth** [comment]
Added this screenshot:

![budgie desktop](https://cloud.githubusercontent.com/assets/3755396/14654119/c2aa78ce-0699-11e6-91ff-dced22f4dd62.png)

Can be found at: https://github.com/budgie-remix/assets/tree/master/Screenshots/FinalRelease/ . Planning to add more screenshots there for final release. :relaxed:
