### ISSUE TITLE
Need to translate the slideshow text to other languages too

### ISSUE THREAD

**Issue by fossfreedom** [budgie-remix/ubiquity-slideshow-budgie-remix#3]
Currently the slideshow deck is in _English_. Need to upload this into launchpad and ask the wonderful launchpad translation community to translate. :relaxed:

**Comment by RohanVilloth** [comment]
Does your previous commit (https://github.com/budgie-remix/ubiquity-slideshow-budgie-remix/commit/0013ca9bc410752234d900a0a2fc3bcc3d92c4ae) solve this translations issue?:confused:

**Comment by fossfreedom** [comment]
> Does your previous commit (https://github.com/budgie-remix/ubiquity-slideshow-budgie-remix/commit/0013ca9bc410752234d900a0a2fc3bcc3d92c4ae) solve this translations issue? :confused:

No.  That was needed I thought to get around a installation issue.
